# Generated by Django 5.2.1 on 2025-05-30 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_listing_created_at_remove_listing_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='end_date',
            new_name='check_in_date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='start_date',
            new_name='check_out_date',
        ),
        migrations.AlterField(
            model_name='booking',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
